In [7]:
import numpy as np

# One dimensional array

In [8]:
a = [1,2,3,4,5] 
b = np.array(a) 
b

array([1, 2, 3, 4, 5])

In [9]:
type(b)

numpy.ndarray

In [10]:
a = [] 
size  = int(input("Enter size:")) 
for i in range(size):
    val = int(input("Enter number:")) 
    a.append(val) 
    
print(a) 
b = np.array(a) 
b

[12, 12, 13]


array([12, 12, 13])

# Two dimensional array

In [11]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# How to check size and dimension of an array  ?

In [12]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print("Total Dimensions :" , b.ndim) 
print("Shape of an array :" , b.shape) #shape = n(rows), n(columns)
print("Total Elements = " , b.size)  ### size = row*column  = total_element 

Total Dimensions : 2
Shape of an array : (3, 3)
Total Elements =  9


# Numpy Functions ==> 



# 1 . Zeros ==> This function create an array (either one dimensional or multi dimensional) and fill all the values with zeros . 

In [14]:
import numpy as np 
a = np.zeros(3) 
a

array([0., 0., 0.])

In [15]:
b = np.zeros([2,3]) 
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
b = np.zeros((2,3)) 
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
b.ndim

2

In [18]:
a

array([0., 0., 0.])

In [19]:
a.ndim

1

# 2 . Ones ==> This function creats an array (either one dimensional or multi dimensional) and fill all the values with one . 

In [20]:
import  numpy as np 
a = np.ones(5) 
a

array([1., 1., 1., 1., 1.])

In [85]:
b = np.ones((2,3,6)) 
b

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

# 3 . eye ==> This function creats an array with all the digonal elements as 1 and rest are 0(In square matrix). In non-square matrix the value are sstill one for digonal (upto which it can draw digonal ) and rest are zero . 

In [22]:
import numpy as np 
a = np.eye(3)         # n(rows) = n(columns) ==> Symmatric Matrix 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
b = np.eye(3,4)    # n(rows) != n(columns) ==> ASymmatric Matrix 
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 4 . diag ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero . 

In [86]:
import numpy as np
a = np.diag([1,4,8,9,15])
a

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  8,  0,  0],
       [ 0,  0,  0,  9,  0],
       [ 0,  0,  0,  0, 15]])

# 5 . randint ==> This  function is used to generate a random number between a given range . 

# syntax == randint(min_value , max_value , total_numbers) 

In [25]:
import numpy as np 
a = np.random.randint(1,10,3) 
a

array([4, 6, 8], dtype=int32)

# 6 . rand() ==> This function is used to generate a random number between 0 to 1 . 

# syntax == rand(numberof values) 

In [26]:
import numpy as np 

a = np.random.rand(5) 
a

array([0.86524273, 0.21791731, 0.87216159, 0.50229798, 0.92685734])

# 7 . randn() ==> This function is used to generate a random number from -3 to close 3 . This may return positive or negative numbers as well . 

# syntax == random.randn(number of values) 

In [27]:
import numpy as np 
a = np.random.randn(1000) 
a

array([-5.13278780e-01,  4.57826585e-01,  3.04250932e+00, -1.14107928e+00,
        1.14812544e+00, -3.52742840e-01,  2.75378200e-01,  1.55037275e+00,
       -1.72570158e-01,  1.28941689e+00,  4.58360103e-01,  6.82723141e-01,
        9.00023691e-01, -9.88539941e-01, -9.31837559e-01,  1.04665801e+00,
       -1.13736435e+00,  4.46854435e-01,  8.58737355e-01,  4.09449435e-01,
        7.59677268e-01,  5.94845875e-01,  6.12931328e-01,  2.79428954e-01,
       -9.38133617e-01, -1.40852707e+00,  1.50782089e+00, -2.48370232e-01,
       -1.71156305e+00,  5.13461647e-01,  2.91652663e-01,  8.41077979e-01,
        1.13311601e+00,  1.76359651e+00,  6.68526461e-01,  2.45424206e+00,
        4.79074261e-01, -2.90195015e-01, -1.18999640e+00, -8.04540852e-01,
        1.55561307e+00, -2.38223321e-01, -1.73852420e+00,  1.32595515e-01,
       -2.85984723e-01, -8.61272006e-02,  4.53106415e-01, -6.56534008e-01,
        1.36311941e+00, -6.45299233e-01, -1.39173664e+00, -6.36149168e-01,
       -1.51095136e+00, -

# Reshaping Data

In [28]:
# n(rows) * n(columns) = n(total_elements) ===> condition always True 

In [29]:
import numpy as np 
a = np.random.randint(1,50,12) 
a

array([46, 11, 40, 35, 34,  5,  4, 14, 12, 18, 18, 24], dtype=int32)

In [30]:
# n(rows) * n(columns) = n(total_elements) 

In [31]:
a.shape 

(12,)

In [32]:
a.reshape(2,6) 
# a

array([[46, 11, 40, 35, 34,  5],
       [ 4, 14, 12, 18, 18, 24]], dtype=int32)

In [33]:
a.reshape(6,2) 
# a

array([[46, 11],
       [40, 35],
       [34,  5],
       [ 4, 14],
       [12, 18],
       [18, 24]], dtype=int32)

In [34]:
a.reshape(3,4) 
# a

array([[46, 11, 40, 35],
       [34,  5,  4, 14],
       [12, 18, 18, 24]], dtype=int32)

In [35]:
a = a.reshape(4,3) 
a

array([[46, 11, 40],
       [35, 34,  5],
       [ 4, 14, 12],
       [18, 18, 24]], dtype=int32)

In [36]:
a = a.reshape(12,1) 
a

array([[46],
       [11],
       [40],
       [35],
       [34],
       [ 5],
       [ 4],
       [14],
       [12],
       [18],
       [18],
       [24]], dtype=int32)

# principal of -1 

In [37]:
a = a.reshape(-1 , 4) 
a

array([[46, 11, 40, 35],
       [34,  5,  4, 14],
       [12, 18, 18, 24]], dtype=int32)

# Seed Function ()  ==> We know that randint function generates random numbers . Everytime we run the program  , new set of random number is generated . So , solve this problem we will use seed function . 

In [103]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [89]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [90]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [41]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [42]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [43]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [44]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [45]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [46]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [47]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [48]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

#### np.random.seed(111) 
a = np.random.randint(1,500,30).reshape(6,5) 
a

# View Vs Copy ==> When we slice a sub-array from an array , it may be done by two ways . 

In [108]:
import numpy as np 
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6] 
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

# copy 

In [105]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6].copy() 
b[:] = 0 
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [51]:
b

array([0, 0, 0])

# conditional selection 

In [52]:
import numpy as np 
a = np.arange(1,16) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [54]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [ ]:
b = a>10 
a[]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

# Operations on Array 

In [111]:
import numpy as np 
a = np.arange(1,5) 
print(a)
print(a*2)
print(a)


[1 2 3 4]
[2 4 6 8]
[1 2 3 4]


In [58]:
a+2 

array([3, 4, 5, 6])

In [59]:
a**2

array([ 1,  4,  9, 16])

In [125]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [123]:
a  = np.array([1,2,3,4])
a.resize(3,3)
print(a)



[[1 2 3]
 [4 0 0]
 [0 0 0]]


In [113]:
b = np.array([5,6,7,8]).reshape(2,2) 
b

array([[5, 6],
       [7, 8]])

In [126]:
a

array([[1, 2],
       [3, 4]])

In [127]:
b

array([[5, 6],
       [7, 8]])

In [62]:
a+b 

array([[ 6,  8],
       [10, 12]])

In [63]:
b-a

array([[4, 4],
       [4, 4]])

In [64]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [65]:
a*b

array([[ 5, 12],
       [21, 32]])

In [66]:
a.dot(b)   ##### for matrix multiplication 

array([[19, 22],
       [43, 50]])

# some more important numpy functions 

In [67]:
import  numpy as np 
a = np.array([10,20,30,40,50]) 
np.min(a) 

np.int64(10)

In [68]:
np.max(a)   #it will return maximum value of the array 

np.int64(50)

In [69]:
np.argmin(a)  #it will return indexing of minimum value

np.int64(0)

In [70]:
np.argmax(a)   # it will return indexing of maximum value 

np.int64(4)

In [71]:
np.sqrt(a) 

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [72]:
np.sin(a) 

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements . 

In [73]:
import numpy as np 

a = np.linspace(1,2,5) 
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [129]:
import numpy as np 

np.random.seed(122) 
a = np.random.randint(1,21,9).reshape(3,3) 
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]], dtype=int32)

In [130]:
np.sum(a) 

np.int64(116)

In [131]:
np.sum(a , axis = 0)   #### in numpy , axis = 1 means row wise operaqtion and 
# axis = 0 means coloumn wise operation.

array([36, 40, 40])

In [77]:
np.min(a,axis=1) 

array([11, 13,  3], dtype=int32)

In [78]:
np.max(a) 

np.int32(17)

In [132]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]], dtype=int32)

In [79]:
np.cumsum(a) #### a,b,c,d = a , a+b , a+b+c , a+b+c+d 

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [80]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]], dtype=int32)

# np.unique(arr , return_index = True , return_counts = True) 

returns 3 array . 
1 . the array with unique values . 
2 . the array with respective index value . 
3 . the array with counting of frequencey . 

In [133]:
a = np.array([10,20,30,40,10,20,50]) 
np.unique(a , return_index  = True , return_counts = True) 


(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 6]), array([2, 2, 1, 1, 1]))

In [ ]:
np.unique

UniqueCountsResult(values=array([10, 20, 30, 40, 50]), counts=array([2, 2, 1, 1, 1]))

# horizontal and vertical stacking

In [82]:
a = np.array([1,2,3,4]) 
b = np.array([5,6,7,8]) 
c = np.array([9,10,11,12])
a

array([1, 2, 3, 4])

In [83]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Q.1 = Write statement to import numpy ? 

Q.2 = Create an array using numpy ? 

Q.3 = Create an array of 10 random integers ?

Q.4 = Create an array of elements from  10-20? 

Q.5 = Create an array which contains value 5 , 10 times ? 

Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 

Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 

Q.8 = Concatenate 2D array horizontally and vertically ? 