In [1]:
import numpy as np

# One dimensional array

In [2]:
a = [1,2,3,4,5] 
b = np.array(a) 
b

array([1, 2, 3, 4, 5])

In [3]:
type(b)

numpy.ndarray

In [5]:
a = [] 
size  = int(input("Enter size:")) 
for i in range(size):
    val = int(input("Enter number:")) 
    a.append(val) 
    
print(a) 
b = np.array(a) 
b

Enter size:3
Enter number:13
Enter number:45
Enter number:67
[13, 45, 67]


array([13, 45, 67])

# Two dimensional array

In [6]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# How to check size and dimension of an array  ?

In [7]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print("Total Dimensions :" , b.ndim) 
print("Shape of an array :" , b.shape) #shape = n(rows), n(columns)
print("Total Elements = " , b.size)  ### size = row*column  = total_element 

Total Dimensions : 2
Shape of an array : (3, 3)
Total Elements =  9


# Numpy Functions ==> 



# 1 . Zeros ==> This function create an array (either one dimensional or multi dimensional) and fill all the values with zeros . 

In [1]:
import numpy as np 
a = np.zeros(3) 
a

array([0., 0., 0.])

In [2]:
b = np.zeros((2,3)) 
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
b.ndim

2

In [4]:
a.ndim

1

# 2 . Ones ==> This function creats an array (either one dimensional or multi dimensional) and fill all the values with one . 

In [17]:
import  numpy as np 
a = np.ones(5) 
a

array([1., 1., 1., 1., 1.])

In [18]:
b = np.ones((2,3)) 
b

array([[1., 1., 1.],
       [1., 1., 1.]])

# 3 . eye ==> This function creats an array with all the digonal elements as 1 and rest are 0(In square matrix). In non-square matrix the value are sstill one for digonal (upto which it can draw digonal ) and rest are zero . 

In [13]:
import numpy as np 
a = np.eye(3)         # n(rows) = n(columns) ==> Symmatric Matrix 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
b = np.eye(3,4)    # n(rows) != n(columns) ==> ASymmatric Matrix 
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 4 . diag ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero . 

In [21]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# 5 . randint ==> This  function is used to generate a random number between a given range . 

# syntax == randint(min_value , max_value , total_numbers) 

In [8]:
import numpy as np 
a = np.random.randint(1,10,3) 
a

array([3, 9, 7])

# 6 . rand() ==> This function is used to generate a random number between 0 to 1 . 

# syntax == rand(numberof values) 

In [9]:
import numpy as np 

a = np.random.rand(5) 
a

array([0.8241922 , 0.87433278, 0.57435913, 0.6254378 , 0.096369  ])

# 7 . randn() ==> This function is used to generate a random number from -3 to close 3 . This may return positive or negative numbers as well . 

# syntax == random.randn(number of values) 

In [4]:
import numpy as np 
a = np.random.randn(1000) 
a

array([-6.92687211e-01, -4.41220792e-01, -5.52330281e-01, -1.64630578e-01,
       -2.47362073e+00,  5.10038256e-01,  1.33452375e+00,  3.39520171e-01,
       -3.12674634e-01,  6.66993301e-01, -8.04645760e-01, -4.03541955e-01,
       -1.42866949e+00,  4.28656133e-01, -6.83073654e-01, -2.23389645e+00,
        4.93632536e-01, -6.20160568e-01,  1.57747166e+00, -3.13192519e-01,
       -1.29077137e+00,  1.40778708e+00, -4.68454321e-01, -3.22483437e-01,
        1.23716007e+00,  5.46339158e-01, -1.07192490e-01,  5.64798302e-01,
        6.07083615e-01, -1.68524657e+00,  3.06979466e-01, -1.47995516e+00,
        4.17558847e-01,  2.66955558e-01, -4.49812529e-01, -1.03993057e+00,
       -4.86556455e-01, -2.26461155e+00, -9.77050937e-01, -1.00261086e+00,
       -1.45094109e-01, -5.73263251e-01,  4.13099139e-01,  2.82213336e-01,
       -1.81281097e+00,  1.37582545e+00,  8.77834640e-01, -2.42554782e-01,
       -7.52236923e-01, -4.39280556e-01, -1.85915408e+00, -1.22540272e+00,
        9.04084607e-01,  

# Reshaping Data

In [31]:
# n(rows) * n(columns) = n(total_elements) ===> condition always True 

In [11]:
import numpy as np 
a = np.random.randint(1,50,12) 
a

array([46, 29, 36, 23,  5, 13,  9, 49, 10, 41, 29, 15])

In [12]:
# n(rows) * n(columns) = n(total_elements) 

In [13]:
a.shape 

(12,)

In [14]:
a.reshape(2,6) 
# a

array([[46, 29, 36, 23,  5, 13],
       [ 9, 49, 10, 41, 29, 15]])

In [15]:
a.reshape(6,2) 
# a

array([46, 29, 36, 23,  5, 13,  9, 49, 10, 41, 29, 15])

In [36]:
a.reshape(3,4) 
# a

array([[44, 36, 15, 39],
       [ 7, 30,  8,  3],
       [47, 46, 46,  2]])

In [37]:
a = a.reshape(4,3) 
a

array([[44, 36, 15],
       [39,  7, 30],
       [ 8,  3, 47],
       [46, 46,  2]])

In [38]:
a = a.reshape(12,1) 
a

array([[44],
       [36],
       [15],
       [39],
       [ 7],
       [30],
       [ 8],
       [ 3],
       [47],
       [46],
       [46],
       [ 2]])

# principal of -1 

In [40]:
a = a.reshape(-1 , 4) 
a

array([[44, 36, 15, 39],
       [ 7, 30,  8,  3],
       [47, 46, 46,  2]])

# Seed Function ()  ==> We know that randint function generates random numbers . Everytime we run the program  , new set of random number is generated . So , solve this problem we will use seed function . 

In [7]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
import numpy as np 

np.random.seed(50) 
a = np.random.randint(1,100 , 10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

#### np.random.seed(111) 
a = np.random.randint(1,500,30).reshape(6,5) 
a

# View Vs Copy ==> When we slice a sub-array from an array , it may be done by two ways . 

In [50]:
import numpy as np 
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6] 
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

# copy 

In [52]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6].copy() 
b[:] = 0 
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [53]:
b

array([0, 0, 0])

# conditional selection 

In [54]:
import numpy as np 
a = np.arange(1,16) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [56]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [57]:
b = a>10 
a[b]

array([11, 12, 13, 14, 15])

In [58]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

# Operations on Array 

In [59]:
import numpy as np 
a = np.arange(1,5) 
print(a)
print(a*2)

[1 2 3 4]
[2 4 6 8]


In [60]:
a+2 

array([3, 4, 5, 6])

In [61]:
a**2

array([ 1,  4,  9, 16])

In [62]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [63]:
b = np.array([5,6,7,8]).reshape(2,2) 
b

array([[5, 6],
       [7, 8]])

In [64]:
a+b 

array([[ 6,  8],
       [10, 12]])

In [65]:
b-a

array([[4, 4],
       [4, 4]])

In [66]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [67]:
a*b

array([[ 5, 12],
       [21, 32]])

In [68]:
a.dot(b)   ##### for matrix multiplication 

array([[19, 22],
       [43, 50]])

# some more important numpy functions 

In [69]:
import  numpy as np 
a = np.array([10,20,30,40,50]) 
np.min(a) 

10

In [70]:
np.max(a)   #it will return maximum value of the array 

50

In [71]:
np.argmin(a)  #it will return indexing of minimum value

0

In [72]:
np.argmax(a)   # it will return indexing of maximum value 

4

In [73]:
np.sqrt(a) 

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [74]:
np.sin(a) 

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements . 

In [10]:
import numpy as np 

a = np.linspace(1,2,5) 
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
import numpy as np 

np.random.seed(122) 
a = np.random.randint(1,21,9).reshape(3,3) 
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]], dtype=int32)

In [77]:
np.sum(a) 

116

In [78]:
np.sum(a , axis = 1)   #### in numpy , axis = 1 means row wise operaqtion and 
# axis = 0 means coloumn wise operation.

array([40, 46, 30])

In [15]:
np.min(a,axis=1) 

array([11, 13,  3], dtype=int32)

In [80]:
np.max(a) 

17

In [81]:
np.cumsum(a) #### a,b,c,d = a , a+b , a+b+c , a+b+c+d 

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [82]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

# np.unique(arr , return_index = True , return_counts = True) 

returns 3 array . 
1 . the array with unique values . 
2 . the array with respective index value . 
3 . the array with counting of frequencey . 

In [83]:
a = np.array([10,20,30,40,10,20,50]) 
np.unique(a , return_index  = True , return_counts = True) 


(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [89]:
a = np.array([1,2,3,4]) 
b = np.array([5,6,7,8]) 
c = np.array([9,10,11,12])
a

array([1, 2, 3, 4])

In [91]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [92]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Q.1 = Write statement to import numpy ? 

Q.2 = Create an array using numpy ? 

Q.3 = Create an array of 10 random integers ?

Q.4 = Create an array of elements from  10-20? 

Q.5 = Create an array which contains value 5 , 10 times ? 

Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 

Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 

Q.8 = Concatenate 2D array horizontally and vertically ? 