In [ ]:
# Numpy is an open-source library taht is used for scintific calculation.

# Why Numpy is better than list?

# Numpy( Homogeneous data type) ,List( Hetrogeneous data type)
# Numpy(less time consumption) , List(more time consumption)
# Numpy(less memory consume) , List(more memory consume)

In [1]:
import numpy as np

In [2]:
a=[1,45,89,90]
type(a)

list

In [4]:
b=np.array(a)
b

array([ 1, 45, 89, 90])

In [5]:
c=[[1,2,3],[4,5,6],[7,8,9]]
d=np.array(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print('Total Rows and Column',d.shape) #=> return n(rows,columns)
print('Total Elements',d.size) #=>return rows*column
print('Total Dimentions',d.ndim) 

Total Rows and Column (3, 3)
Total Elements 9
Total Dimentions 2


User Defined Array


In [7]:
size=int(input('Enter the size of Array'))
a=[]
for i in range(size):
    val=int(input('Enter the Value:'))
    a.append(val)
print(a,type(a))
b=np.array(a)
print(b,type(b))

[12, 23, 53] <class 'list'>
[12 23 53] <class 'numpy.ndarray'>


In [8]:
a=[1,2,3]
print(a*3)
b=np.array([1,2,3])
print(b*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


PreDefined Functions of Numpy

In [9]:
# (1). Zero() -> It will create an array in which all the values willbe 0.


In [11]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [13]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# (2). ones() -> It will create an array in which all the values will be 1.

In [12]:
a=np.ones(3)
a

array([1., 1., 1.])

In [15]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# (3). eye() ->It will create an array in which
#  digonal positional elements willbe 1 and
#  rest all are zeros

In [16]:
a=np.eye(5) #n(column) =n(rows) -> Symmatrix Matrics
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
a=np.eye(3,4) #n(column) <> n(rows) -> Asymmatrix Matrics
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
# (4). diag() -> It will create an array taht will set diagonal positional custom values.

In [21]:
a=np.diag([1,23,54612,2341])
a

array([[    1,     0,     0,     0],
       [    0,    23,     0,     0],
       [    0,     0, 54612,     0],
       [    0,     0,     0,  2341]])

Random Module

In [1]:
# Randint() -> It will generate random values based on fixed criteria.

# np.random.randint(min_range,max_range,total_NUmber)

In [4]:
# import random
import numpy as np
a=np.random.randint(1,10,3)
a

array([6, 2, 6], dtype=int32)

In [5]:
# (b) Rand() -> It will generate numbers from 0 to 1.


In [6]:
a=np.random.rand(5)
a

array([0.58260603, 0.70719634, 0.11751172, 0.76659572, 0.73950583])

In [3]:
# (c) seed() -> It willl fix our random genreated data.

In [29]:
import numpy as np
np.random.seed(31)
a=np.random.randint(1,10,3)
a

array([3, 8, 1], dtype=int32)

View vs copy

In [32]:
a=np.array([10,20,30,40,50,60,70,80])  ## View methods
b=a[3:6]
b[:]=0
print(b)
print(a)

[0 0 0]
[10 20 30  0  0  0 70 80]


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])  ## Copy methods
b=a[3:6].copy()
b[:]=0
print(a)
print(b)


[10 20 30 40 50 60 70 80]
[0 0 0]


Reshaping the Array

In [11]:
# n(rows) * n(columns) =n(total_elements)


In [12]:
a=np.random.randint(1,50,12)
a

array([13, 24,  3, 18, 47,  4, 42,  8,  2, 46, 36, 19], dtype=int32)

In [ ]:
# 1*12, 12*1
# 2*6,  6*2
# 3*4 , 4*3

In [13]:
a.reshape(2,6)

array([[13, 24,  3, 18, 47,  4],
       [42,  8,  2, 46, 36, 19]], dtype=int32)

In [14]:
a.reshape(12,1)

array([[13],
       [24],
       [ 3],
       [18],
       [47],
       [ 4],
       [42],
       [ 8],
       [ 2],
       [46],
       [36],
       [19]], dtype=int32)

In [15]:
a.reshape(4,3)

array([[13, 24,  3],
       [18, 47,  4],
       [42,  8,  2],
       [46, 36, 19]], dtype=int32)

In [16]:
a.reshape(3,4)

array([[13, 24,  3, 18],
       [47,  4, 42,  8],
       [ 2, 46, 36, 19]], dtype=int32)

In [36]:
a=np.arange(1,15)
print(a)
a.resize(4,6)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14  0  0  0  0]
 [ 0  0  0  0  0  0]]


Conditional Selection in Numpy

In [17]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [19]:
b=a>10
a[b]

array([11, 12, 13, 14])

In [20]:
print(a[a>10])

[11 12 13 14]


In [21]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [40]:
print(a[a%2==0])

[ 2  4  6  8 10 12 14  0  0  0  0  0  0  0  0  0  0]


In [22]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [23]:
a**2

array([ 1,  4,  9, 16])

In [24]:
a**3

array([ 1,  8, 27, 64])

In [25]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [26]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [27]:
a+b

array([[ 6,  8],
       [10, 12]])

In [28]:
a*b

array([[ 5, 12],
       [21, 32]])

In [29]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a.dot(b) #for matrix multiplication

array([[19, 22],
       [43, 50]])

In [31]:
# # Unique() -> It will return 3 arrays
# (1). Arr  -> unique values store 
# (2). return_index -> True -> In which indexing we have Unique values
# (3). return_counts -> True -> Frequency of each elements

In [41]:
a=np.array([1,2,3,2,1,234,34,2,1,34,2,7,8,7,8,4,2,1,7,8])
a

array([  1,   2,   3,   2,   1, 234,  34,   2,   1,  34,   2,   7,   8,
         7,   8,   4,   2,   1,   7,   8])

In [50]:
np.unique(a,return_index=True,return_counts=True)

(array([  1,   2,   3,   4,   7,   8,  34, 234]),
 array([ 0,  1,  2, 15, 11, 12,  6,  5]),
 array([4, 5, 1, 1, 3, 3, 2, 1]))

In [55]:
y=np.unique_all(a)
print(y)
for ele in y:
    print(ele)

UniqueAllResult(values=array([  1,   2,   3,   4,   7,   8,  34, 234]), indices=array([ 0,  1,  2, 15, 11, 12,  6,  5]), inverse_indices=array([0, 1, 2, 1, 0, 7, 6, 1, 0, 6, 1, 4, 5, 4, 5, 3, 1, 0, 4, 5]), counts=array([4, 5, 1, 1, 3, 3, 2, 1]))
[  1   2   3   4   7   8  34 234]
[ 0  1  2 15 11 12  6  5]
[0 1 2 1 0 7 6 1 0 6 1 4 5 4 5 3 1 0 4 5]
[4 5 1 1 3 3 2 1]


In [73]:
np.unique_counts(a)

UniqueCountsResult(values=array([1, 2, 3, 4]), counts=array([1, 1, 1, 1]))

In [52]:
np.unique(a)

array([  1,   2,   3,   4,   7,   8,  34, 234])

In [ ]:
a.view()

array([  1,   2,   3,   2,   1, 234,  34,   2,   1,  34,   2,   7,   8,
         7,   8,   4,   2,   1,   7,   8])

Stacking in Numpy

In [57]:
# hstack() -> It will combined arrays in horizontally

In [61]:
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)

In [62]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
# vstack -> It will combined the arrays in Vertically

In [71]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
x=np.vstack((a,b,c))
print(x[0][2])

3


In [81]:
print(np.stack((a,b),axis=-1))
print(np.stack((a,b),axis=0))
print(np.stack((a,b),axis=1))
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
