In [ ]:
# Numpy is an open-source library taht is used for scintific calculation.

# Why Numpy is better than list?

# Numpy( Homogeneous data type) ,List( Hetrogeneous data type)
# Numpy(less time consumption) , List(more time consumption)
# Numpy(less memory consume) , List(more memory consume)

In [1]:
import numpy as np

In [2]:
a=[1,45,89,90]
type(a)

list

In [4]:
b=np.array(a)
b

array([ 1, 45, 89, 90])

In [5]:
c=[[1,2,3],[4,5,6],[7,8,9]]
d=np.array(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print('Total Rows and Column',d.shape) #=> return n(rows,columns)
print('Total Elements',d.size) #=>return rows*column
print('Total Dimentions',d.ndim) 

Total Rows and Column (3, 3)
Total Elements 9
Total Dimentions 2


User Defined Array


In [7]:
size=int(input('Enter the size of Array'))
a=[]
for i in range(size):
    val=int(input('Enter the Value:'))
    a.append(val)
print(a,type(a))
b=np.array(a)
print(b,type(b))

[12, 23, 53] <class 'list'>
[12 23 53] <class 'numpy.ndarray'>


In [8]:
a=[1,2,3]
print(a*3)
b=np.array([1,2,3])
print(b*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


PreDefined Functions of Numpy

In [9]:
# (1). Zero() -> It will create an array in which all the values willbe 0.


In [11]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [13]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# (2). ones() -> It will create an array in which all the values will be 1.

In [12]:
a=np.ones(3)
a

array([1., 1., 1.])

In [15]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# (3). eye() ->It will create an array in which
#  digonal positional elements willbe 1 and
#  rest all are zeros

In [16]:
a=np.eye(5) #n(column) =n(rows) -> Symmatrix Matrics
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
a=np.eye(3,4) #n(column) <> n(rows) -> Asymmatrix Matrics
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
# (4). diag() -> It will create an array taht will set diagonal positional custom values.

In [21]:
a=np.diag([1,23,54612,2341])
a

array([[    1,     0,     0,     0],
       [    0,    23,     0,     0],
       [    0,     0, 54612,     0],
       [    0,     0,     0,  2341]])